all: assignmentP2.class dataSet.class dataset_docTable.class FileProcessor.class 

assignmentP2.class: assignmentP2.java
	javac assignmentP2.java 
	
dataSet.class: dataSet.java
	javac dataSet.java 
	
dataset_docTable.class: dataset_docTable.java
	javac dataset_docTable.java

FileProcessor.class: FileProcessor.java
	javac FileProcessor.java

clean:
	rm -f *.class 